### ISSUE TITLE
Help on some downstream feedstocks -fallow-argument-mismatch

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/mpich-feedstock#76] opened 2022-12-04 19:51 UTC
### Comment:

* [ ] https://github.com/conda-forge/conduit-feedstock/pull/27
* [ ] https://github.com/conda-forge/sirius-feedstock/pull/17

Seem to be suffering from a bug you all resolved wrt `-fallow-argument-mismatch`

Your help is a ppreciated

**Comment by dalcinl** [comment] 2022-12-06 00:17
Maybe it is a problem within cmake's FindMPI? I see this line in the logs:
```
-- BLT MPI Compile Flags:  -fallow-argument-mismatch
```
That flag is only valid for Fortran, but maybe cmake is somehow picking it and passing it down to the C compiler?
```
clang-14: error: unknown argument: '-fallow-argument-mismatch'
```

**Comment by dalcinl** [comment] 2022-12-06 11:52
> Looking at the PC file, it does appear as a fflag.

What about running ` mpicc -show` and `mpifort -show`? Any chance cmake's `FindMPI` is picking the flag from the later, but then wrongly adding it to the flags for the C compiler?

**Comment by hmaarrfk** [comment] 2022-12-06 12:32
Thank you for the tips. I likely have limited time. But I'll let the original feedstock maintainers take over with your input here and there!

**Comment by cyrush** [comment] 2023-01-09 17:17
Hi All, 

I found a resolution. 

FindMPI is doing the correct thing, the problem is in conduit's build system.

We have an mpi smoke test that is combining all c + fortran flags reported and passing the combined flags to the c compiler -- which clang is (rightly) unhappy with. 

I have a fix to filter the flags in conduit's build system and avoid the problem that will be in our next release.

**Closed** 2023-01-10 06:46 UTC
Labels: question
